### ISSUE TITLE
SpinupWP caching issue with Elementor page builder

### ISSUE THREAD

**Issue by tamal-sen** [deliciousbrains/spinupwp-plugin#43]
I am facing the following issue with of my sites.

• I have page cache enabled for spinupwp panel

After some time (like 1-3 hours) all the resources under `/wp-content/uploads/elementor/css/post-xxx.css` get 404 error which results in a broken styling of the website. Whenever I clear the cache, the resource is available again. After some time, it will happen again.

I am trying to fix this issue. Can anybody help me pointing in the right direction?

I tried the following:
1. Deactivated other plugins
2. Deactivated page cache from the panel but kept the helper plugin
3. Set Cache duration for 6 hours but it still happens during the period

Now trying:
1. Added exclusion for /uploads/elementor/css/ directory

Thanks.

**Comment by A5hleyRich** [comment]
@tamal-sen this is a bug in Elementor. They are aware of the issue and are working on a fix. The temporary solution is to disable object caching using the following constant:

```
define( 'WP_REDIS_DISABLED', true );
```

Page caching can remain enabled.

**Comment by NickIvanter** [comment]
I'm facing the same problem. @A5hleyRich, is there an open issue for this in the Elementor GitHub repository?

**Comment by NickIvanter** [comment]
I seem to have found an alternative workaround. Perhaps it will be useful to someone:

```
add_action( 'elementor/core/files/clear_cache', function() {
	if ( function_exists( 'spinupwp_purge_site' ) ) {
		spinupwp_purge_site();
	}
} );
```
Seems better than disabling object caching altogether.

**Comment by tamal-sen** [comment]
@NickIvanter can you please confirm if your fix is still working? I'd love to re-enable the redis cache.

**Comment by zeinnicholas** [comment]
> @NickIvanter can you please confirm if your fix is still working? I'd love to re-enable the redis cache.

Yes, this is how you fix this. All SpinupWP has to do is to add this to their Helper plugin. But they rather blame the other guy instead.

You can use this with something like the CodeSnippets plugin, or your child theme.

**Comment by NickIvanter** [comment]
@tamal-sen - I had to add wp_cache_flush() before purging the page cache, see my updated snipped above.

With this code, I haven't seen the issue in a two weeks.

**Comment by tamal-sen** [comment]
> @tamal-sen - I had to add `wp_cache_flush()` before purging the page cache, see my updated snipped above.
> 
> With this code, I haven't seen the issue in a two weeks.

Hey @NickIvanter, thank you.  The snippet is not updated for some reason but I get your point.

**Comment by vandijks** [comment]
I was not able to reproduce it. I added the code (incl. `wp_cache_flush()`) via Code Snippets yesterday, but this morning I again had 404's on the Elementor css files.

**Comment by A5hleyRich** [comment]
@zeinnicholas there's no need for the snarky reply. We haven't added a fix for this issue to the SpinupWP helper plugin because we're unable to replicate the issue ourselves. We're reluctant to add code that we can't confirm fixes the issue.

I'm chasing this up with the Elementor team because clearly, something has got lost in translation.

**Comment by tamal-sen** [comment]
Hey @A5hleyRich I have a staging server where this exact issue persists. I'd be happy to help you with the env if you are unable to replicate the issue.

**Comment by zeinnicholas** [comment]
@A5hleyRich fair enough. I removed the offending part. I apologize if I was unfair or misleading. I know you guys are very dedicated and serious people!

**Comment by A5hleyRich** [comment]
@tamal-sen would you mind testing the following updated SpinupWP plugin resolves your issue? It includes the purge cache logic provided by @NickIvanter.

[spinupwp.zip](https://github.com/deliciousbrains/spinupwp-plugin/files/5776687/spinupwp.zip)

**Comment by tamal-sen** [comment]
> @tamal-sen would you mind testing the following updated SpinupWP plugin resolves your issue? It includes the purge cache logic provided by @NickIvanter.
> 
> [spinupwp.zip](https://github.com/deliciousbrains/spinupwp-plugin/files/5776687/spinupwp.zip)

Hey @A5hleyRich I actually tried @NickIvanter's code (by adding it in my theme's functions.php) but unfortunately, it didn't work for me, the CSS files were still missing. Anyway, I will update my SpinupWP plugin nevertheless and will let you know.

**Comment by vandijks** [comment]
> @tamal-sen would you mind testing the following updated SpinupWP plugin resolves your issue? It includes the purge cache logic provided by @NickIvanter.
> 
> [spinupwp.zip](https://github.com/deliciousbrains/spinupwp-plugin/files/5776687/spinupwp.zip)

I did install the updated SpinupWP plugin on one of my effected servers yesterday @A5hleyRich No luck I am afraid. 

Like @tamal-sen I also previously added @NickIvanter code without succes.

**Comment by A5hleyRich** [comment]
@tamal-sen @vandijks thanks for testing. I was able to see the problem first-hand using **Elementor > Tools > Regenerate CSS** and confirm the fix. It's my understanding that Elementor is updating the CSS styles on a cron schedule. But, it's that process that we're unable to replicate. Are you aware of any specific settings required for this action to happen? Also, what output do you get if you run `wp cron event list` for the affected site? If either of you could export your Elementor settings, that might also help.

**Comment by vandijks** [comment]
<img width="570" alt="Screenshot 2021-01-07 at 13 55 07" src="https://user-images.githubusercontent.com/9658127/103895170-43838d00-50f0-11eb-9c2b-ea3035546c8e.png">

@A5hleyRich I will make a clone of one of my effected servers and will send you the login details per e-mail. I will also send you the other information requested above.

I have some servers that are effected and others not. I am not sure if it is related, and I am also not sure if this is the case all the time, but on the severs I work on daily, I do not see the css 404 issues. 

The clone of the server effected is a super simple website, fresh out of the box install with Elementor Pro.

**Comment by tamal-sen** [comment]
![image](https://user-images.githubusercontent.com/71141953/103918507-16a79800-5139-11eb-8e91-4727cd0e9be3.png)
Here is the output of `wp cron event list` @A5hleyRich

**Comment by A5hleyRich** [comment]
@tamal-sen any chance I can get the output from this command too? `wp plugin list`

**Comment by tamal-sen** [comment]
@A5hleyRich sure.
![image](https://user-images.githubusercontent.com/71141953/104024721-c2122480-51ed-11eb-971b-0ded10a733d0.png)

**Comment by A5hleyRich** [comment]
Received from Elementor support today:

> I have just checked in our internal system and I see that the
appropriated report is already created there for our developers. I
will add this ticket there as well to make its priority even higher.
Thanks for the links to GitHub issues, as I'm going to attach them
there too.
> 
> And regarding this issue, it appears that the wp-content/uploads/css/
files are removed when the caching lifetime expires and those files
never regenerated back but still stored in the object cache. You have
to clear the object cache to remove the 404 errors that start
appearing.
I apologize for any inconvenience caused by this issue, but
unfortunately, I don't have any ETA on when a fix will be released.

**Comment by actionTurtle** [comment]
Last update was 21 days ago? Any news on what's going on or when this might be patched? Thanks!!

**Comment by A5hleyRich** [comment]
We've just pushed an update to the SpinupWP WordPress plugin that adds compatibility for Elementor. The SpinupWP plugin upgrade should be available from the WP dashboard. In our testing, this resolves issues with styles breaking during the night, but it would be great to have further confirmation.

**Comment by vandijks** [comment]
I did update a few of my sites Ashley, but the the issues persists I am afraid.

**Comment by vandijks** [comment]
In my case the problem has gotten worse. First I had the issue sometimes, now it seems to happen all the time or at least since I updated the SpinupWP plugin.

**Comment by A5hleyRich** [comment]
@vandijks what sort of frequency are we talking about? The issue that we've had tracking this down, is that Elementor doesn't schedule any cron events to clear the CSS files, so something else is triggering that to happen. Elementor has a single method for purging all its generated CSS files, which is only fired a handful of times, which SpinupWP now hooks into to clear the site's caches. This has resolved the Elementor caching issue for a number of customers. Would it be possible to get a clone of your problematic site again?

**Comment by vandijks** [comment]
Hi @A5hleyRich Basically every morning, so once a day. Somewhere during the nightie issue returns. The thing is that some off my Elementor websites deployed with SpinupWP have no issues at all, while others seem to have more frequent issues. I have not found any correlation yet. I am happy to make a clone or can give you sudo access. Will send you a private message.

**Comment by A5hleyRich** [comment]
We've got a dev build of the SpinupWP plugin available which we believe resolves the remaining Elementor issues. We're testing it on a few customer sites at the moment before releasing it on wp.org. Build available here:

[spinupwp.zip](https://github.com/deliciousbrains/spinupwp-plugin/files/5952868/spinupwp.zip)

**Comment by kcolemangt** [comment]
The usual problems persist on my sites with this dev version. I'm reverting to the temporary fix of `define( 'WP_REDIS_DISABLED', true );` because I need working sites more than I need fast-but-broken sites 🤣 

I still recommend SpinupWP but any new users who also use Elementor are in for a bad surprise when their sites start breaking every day until they find this temp fix. Popping up a warning and link to the temp fix at setup time would have improved my initial experience.

**Comment by kcolemangt** [comment]
@vandijks @NickIvanter @tamal-sen Are you able to use the page cache?

These steps are easily reproducible on my sites:

1. Enable page cache
2. Elementor > Tools > Regenerate file
3. Hard reload to see the broken page
4. Disable page cache
5. Hard reload and the page is fixed

In step 3, the page breaks because one or more of the css files cannot be loaded (404). 
`/wp-content/uploads/elementor/css/global.css?ver=1615478725` or 
`/wp-content/uploads/elementor/css/post-XXXX.css?ver=1615479864`
are examples of paths that fail. Other similar paths load correctly.

Attempting to fetch the broken path directly by opening in a new tab or `curl` fails until I disable the page cache.

Adding `/wp-content/` to the page cache path exclusions works for a second but probably because the change clears the cache. `Elementor > Tools > Regenerate` file breaks it again. Adding `/` to path exclusions works but effectively disables the entire page cache.

I'm using the latest elementor (3.1.4) and elementor pro (3.1.1) with spinupwp plugin version that @A5hleyRich posted to this thread on Feb 9.

Reverting to the wp.org released version of spinupwp (v 1.3) and adding `define( 'WP_REDIS_DISABLED', true );` to `wp-config.php` produces the same behavior. Steps 1-5 can be reproduced even after deleting the spinupwp plugin with or without `define( 'WP_REDIS_DISABLED', true );`

`/etc/nginx/sites-available/SITE.com/server/fastcgi-cache.conf` is created when page cache is enabled for a site. It contains several clues about spinupwp's page cache challenges.

Here's another clue about spinupwp page cache altering the behavior:

1. With page cache disabled, `wp-content/uploads/elementor/css/` contains all of the necessary files like global.css, post-XXXX.css, etc to render the site properly.
2. Enable page cache
3. Regenerate files
4. Hard reload page (broken site)
5. `wp-content/uploads/elementor/css/` only contains a few of the necessary files
6. Disable page cache
7. Hard reload page (working site)
8. `wp-content/uploads/elementor/css/` contains all of the necessary files

Seems like page cache is interfering with how elementor is triggered to generate its style files.

While these generated files are recommended for performance reasons (such as being cached at CDN edges), it's possible to render the site without them. 

Elementor > Settings > Advanced > CSS Print Method

- External file. _Use external CSS files for all generated stylesheets. Choose this setting for better performance (recommended)._ 
- Internal embedding. _Use internal CSS that is embedded in the head of the page. For troubleshooting server configuration conflicts and managing development environments._

It looks like either internal css embedding or disabling page cache are the best temporary fixes. Either way, performance suffers.

**Comment by DODMax** [comment]
Maybe it's time to add an option in the SpinupWP admin interface to disable object caching?
Personally I've been struggling with this issues with most of my Elementor websites since Elementor 3.
I still have production websites break because I forget to SSH into servers and add `define( 'WP_REDIS_DISABLED', true );`
PS: forgive my response not being directly related to this repo.

**Comment by andyhza** [comment]
@A5hleyRich Running a number of sites with Elementor, I did not experience this issue until I cloned the sites to another server (AWS EC2 t3 small instances) and then this issue started happening on the cloned sites (and not on the same originally created sites). Not sure whether this is a clue for you but thought this finding worth mentioning as it happened consistently to the two sites I cloned.

**Comment by shilo-ey** [comment]
@A5hleyRich Shilo from Elementor here,

Can you please see the comment [I added here](https://github.com/elementor/elementor/issues/13299#issuecomment-814987444) as a troubleshooting option?

Thanks

**Comment by heyfletch** [comment]
@A5hleyRich @shilo-ey this fix seems to have stalled. It seems there is a beta SpinupWP plugin that does extra cache clearing, and a [suggestion from Elementor](https://github.com/elementor/elementor/issues/13299#issuecomment-814987444) about changing an autoload parameter. Does anyone know if either or both of these methods are fixing this issue? My Elementor websites are slower than they need to be on SpinupWP, and I'm awaiting an official fix.

**Comment by shilo-ey** [comment]
This issue has been resolved in Elementor v3.3.0

Feel free to update

Thanks!

**Comment by A5hleyRich** [comment]
Thanks @shilo-ey

**Comment by cpiechotta** [comment]
I'm still seeing this issue on Elementor 3.17.3 and SpinupWP 1.5.1

Overnight the CSS cache from Elementor seems to be rebuild as already explained in the thread and on the next day I have to manually clear the page cache for the CSS to not produce a 404. Note: clearing the object cache is not neccesary it seems.

**Comment by fonderco** [comment]
> @A5hleyRich I'm still seeing this issue on Elementor 3.17.3 and SpinupWP 1.5.1
> 
> Overnight the CSS cache from Elementor seems to be rebuild as already explained in the thread and on the next day I have to manually clear the page cache for the CSS to not produce a 404. Note: clearing the object cache is not neccesary it seems.
> 
> We're using SpinupWP with WPRocket and Elementor.

I have the exact same setup and getting the same issue.  Any resolution?
